name: OpenLight
version: '${project.version}'
main: me.knifeworm.openlight.OpenLight
api-version: 1.18
authors: [ knifeworm ]
description: Open source plugin.
website: https://github.com/knifeworm/OpenLightPlugin
commands:
  gmc:
    description: Sets your or another persons gamemode to creative.
    aliases:
      - creative
  gms:
    description: Sets your or another persons gamemode to survival.
    aliases:
      - survival
  gmsp:
    description: Sets your or another persons gamemode to spectator.
    aliases:
      - spectator
  gma:
    description: Sets your or another persons gamemode to adventure.
    aliases:
      - adventure
  fly:
    description: Puts fly mode on you or another person.
    aliases:
      - fly